version: '3.8'
services:
  angular:
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - node_modules_angular:/app/node_modules
    restart: on-failure
    networks:
      - my-network

# volumes
volumes:
  node_modules_angular: {}

# networks
networks:
  my-network:
    name: full-project-setup-network
    external: true
